---
title: "Homework 1"
author: Jiayi Zhou
output: github_document
---

This is my solution to HW1.

```{r}
library(tidyverse)
```

## Problem 1

Create a data frame with specified elements

```{r}
prob1_df = 
  tibble(
    samp = rnorm(10),
    logi_vec = samp > 0,
    char_vec = c("a", "b", "c", "d", "e", "f", "g", "h", "i", "j"),
    fac_vec = factor(c("low", "low", "low", "low", "mod", "mod", "mod", "high", "high", "high"))
  )
```

Take the mean of each variable in my data frame.

```{r}
mean(pull(prob1_df, samp))
mean(pull(prob1_df, logi_vec))
mean(pull(prob1_df, char_vec))
mean(pull(prob1_df, fac_vec))
```

I can take the mean of numerical and logical variables but not character or factor.

```{r}
as.numeric(pull(prob1_df, samp))
as.numeric(pull(prob1_df, logi_vec))
as.numeric(pull(prob1_df, char_vec))
as.numeric(pull(prob1_df, fac_vec))
```

converting logical vector to numeric vector, factor, and first to factor then to numeric.
```{r}
as.numeric(pull(prob1_df, logi_vec)) * pull(prob1_df, samp)
as.factor(pull(prob1_df, logi_vec)) * pull(prob1_df, samp)
as.numeric(as.factor(pull(prob1_df, logi_vec))) * pull(prob1_df, samp)
```


